<?php
/**
 * Created by PhpStorm.
 * User: frontend
 * Date: 13/01/17
 * Time: 11:41 AM
 */

$messages = array(
    "text" => '
<?xml version="1.0" encoding="UTF-8"?>
<urlset
      xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<!-- created with Free Online Sitemap Generator www.xml-sitemaps.com -->
<url>
  <loc>http://www.xoximilco.com/en/</loc>
  <changefreq>daily</changefreq>
  <priority>1.00</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/en/xoximilco-cancun/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/en/about-xoximilco/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/en/gastronomy-in-xoximilco/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/en/xoximilco-facilities/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/en/how-to-get-to-xoximilco/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/en/specials-events-in-xoximilco</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/en/xoximilco-cancun-weddings/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/en/xoximilco-tour/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/en/xoximilco-cancun-promotions/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/en/xoximilco-cancun-packages/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/en/promotions/xoximilco-group/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/en/faqs/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/en/cancun-riviera-maya/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/en/terms-of-use/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/en/privacy-notice/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/en/site-map/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
</urlset>
'
);