<?php
/**
 * Created by PhpStorm.
 * User: frontend
 * Date: 13/01/17
 * Time: 11:41 AM
 */

$messages = array(
    "text" => '
<?xml version="1.0" encoding="UTF-8"?>
<urlset
      xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<!-- created with Free Online Sitemap Generator www.xml-sitemaps.com -->
<url>
  <loc>http://www.xoximilco.com/es/</loc>
  <changefreq>daily</changefreq>
  <priority>1.00</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/es/xoximilco/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/es/acerca-de-xoximilco/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/es/cena-cancun/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/es/instalaciones-xoximilco/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/es/ubicacion-xoximilco/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/es/eventos-especiales/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/es/bodas-xoximilco/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/es/entrada-xoximilco/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/es/promociones/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/es/paquetes/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/es/quintanarroense/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/es/preguntas-frecuentes/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/es/cancun-y-riviera-maya/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/es/terminos-de-uso/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/es/mapa-de-sitio/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/es/promociones/xoximilco-grupo/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>http://www.xoximilco.com/es/promociones/quintanarroense-6x5/</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
</urlset>
'
);